# Generated by Django 5.2.12 on 2026-03-30 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvUpload', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='applicants',
            new_name='applicant',
        ),
    ]
