# Generated by Django 5.2.12 on 2026-04-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvUpload', '0002_rename_applicants_applicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='resume_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
