# Generated by Django 5.2.12 on 2026-05-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvUpload', '0003_applicant_resume_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='cleaned_resume_text',
            field=models.TextField(blank=True),
        ),
    ]
