# Generated by Django 5.2.12 on 2026-06-08 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvUpload', '0004_applicant_cleaned_resume_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='cleaned_resume_text',
        ),
    ]
