# Generated by Django 5.2.12 on 2026-06-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvUpload', '0005_remove_applicant_cleaned_resume_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
